apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: quarkus-test-1 
  janus-idp.io/tekton: quarkus-test-1
  backstage.io/kubernetes-id: quarkus-test-1
  backstage.io/kubernetes-namespace: kesavramk95-development 
  app.kubernetes.io/part-of: quarkus-test-1
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  